name: unit tests
on: workflow_call
concurrency:
  group: run-unit-tests
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-slim
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - run: corepack enable
      - name: Enable Yarn cache
        uses: actions/cache@v6
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn test
